project_id = "qufalwhsuvvxcehvysdj"

[functions]
  [functions.admin-user-action]
    verify_jwt = true
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.moderate-content]
    verify_jwt = true
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-auth-email]
    verify_jwt = false
  [functions.send-bulk-blast]
    verify_jwt = false
  [functions.send-email]
    verify_jwt = true
  [functions.send-notification-email]
    verify_jwt = true
  [functions.send-ses-email]
    verify_jwt = true
  [functions.sitemap]
    verify_jwt = false
  [functions.track-email-open]
    verify_jwt = false
